<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Figma Export</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
<div style="width: 1440px; height: 1000px; position: relative; background: #537ADD; overflow: hidden">
  <div style="width: 1440px; height: 203px; left: 0px; top: 0px; position: absolute; background: #5DE285; overflow: hidden">
    <div style="left: 1033px; top: 56px; position: absolute; justify-content: flex-end; align-items: center; gap: 48px; display: inline-flex">
      <div style="justify-content: center; display: flex; flex-direction: column; color: black; font-size: 20px; font-family: Inter; font-weight: 500; line-height: 30px; word-wrap: break-word">home</div>
      <div style="justify-content: center; display: flex; flex-direction: column; color: black; font-size: 20px; font-family: Inter; font-weight: 500; line-height: 30px; word-wrap: break-word">review</div>
      <div style="padding-left: 24px; padding-right: 24px; padding-top: 14px; padding-bottom: 14px; box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.05); border-radius: 8px; justify-content: center; align-items: center; gap: 8px; display: flex">
        <div style="justify-content: center; display: flex; flex-direction: column; color: black; font-size: 16px; font-family: Inter; font-weight: 500; line-height: 24px; word-wrap: break-word">services</div>
      </div>
    </div>
    <div style="left: 80px; top: 67px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: black; font-size: 20px; font-family: Inter; font-weight: 500; line-height: 30px; word-wrap: break-word">Game Platform</div>
  </div>
  <div style="width: 609px; height: 278px; left: 135px; top: 293px; position: absolute; overflow: hidden">
    <div style="width: 716px; height: 407px; left: 0px; top: -65px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: black; font-size: 64px; font-family: Inter; font-weight: 500; line-height: 96px; word-wrap: break-word">Game Store<br/></div>
  </div>
  <img style="width: 270px; height: 337px; left: 135px; top: 581px; position: absolute; border-radius: 20px" src="https://placehold.co/270x337" />
  <div style="width: 264px; height: 49px; left: 164px; top: 925px; position: absolute; color: black; font-size: 50px; font-family: Inter; font-weight: 400; word-wrap: break-word">${games.name}</div>
  <img style="width: 612px; height: 337px; left: 446px; top: 581px; position: absolute; border-radius: 28px" src="https://placehold.co/612x337" />
  <div style="width: 305px; height: 67px; left: 646px; top: 925px; position: absolute; color: black; font-size: 50px; font-family: Inter; font-weight: 400; word-wrap: break-word">${games.name}</div>
  <img style="width: 331px; height: 337px; left: 1090px; top: 581px; position: absolute; border-radius: 23px" src="https://placehold.co/331x337" />
  <div style="width: 224px; height: 52px; left: 1169px; top: 925px; position: absolute; color: black; font-size: 50px; font-family: Inter; font-weight: 400; word-wrap: break-word">${games.name}</div>
  <div style="width: 1168px; height: 75px; left: 135px; top: 496px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: black; font-size: 64px; font-family: Inter; font-weight: 500; line-height: 96px; word-wrap: break-word">Here are your published games:</div>
</div>
</body>
</html>