<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" type="text/css" href="/css/styless.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Exile&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <title>Login Page</title>
</head>
<body>
    <section class="container">
        <div class="left-side">
            <form>
            <h1>Customer Login</h1>
            <span class="please">Please login to continue to your account.</span>
            <input placeholder="  Email" type="email">
            <input placeholder="  Password" type="password">
            <button class="dev-change">Switch to Developer</button>
            <button class="sign-button">Sign in</button>
            <div class="do"><hr><span class="or-span">or</span><hr></div>
            <span class="need">Need an account? <span class="create-span">Create one</span></span>
            </form>
        </div>
        <div class="right-side">
            <div><img src="game1.png"></div>
            
        </div>
    </section>
</body>
</html>