<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">

  <title>Figma Export</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
<div style="width: 1440px; height: 1024px; background: white; overflow: hidden; border-radius: 32px; justify-content: flex-start; align-items: flex-start; display: inline-flex">
  <div style="flex: 1 1 0; align-self: stretch; padding: 32px; position: relative; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: inline-flex">
    <div style="align-self: stretch; flex: 1 1 0; padding-left: 64px; padding-right: 64px; flex-direction: column; justify-content: center; align-items: flex-start; gap: 32px; display: flex">
      <div style="align-self: stretch; flex-direction: column; justify-content: center; align-items: flex-start; gap: 12px; display: flex">
        
  <div class="container">
    <h1>Edit Login Information</h1>
    <form action="/Developers" method="post">
      <label for="username"> Username</label>
      <input type="text" id="username" name="username" placeholder="Enter Your Username" required>

      <label for="password">Password</label>
      <input type="password" id="password" name="password" placeholder="Enter Your Password" required>

      
      <button type="submit">Save Changes</button>
    </form>

      </div>
    </div>
    <div style="width: 396px; height: 54px; padding-top: 16px; padding-bottom: 16px; padding-right: 16px; left: 96px; top: 628px; position: absolute; border-radius: 10px; outline: 1px #D9D9D9 solid; outline-offset: -1px; justify-content: center; align-items: center; gap: 10px; display: inline-flex">
      <div style="width: 189px; height: 22px; color: black; font-size: 18px; font-family: Inter; font-weight: 600; line-height: 21.60px; word-wrap: break-word"> Switch to Customer</div>
    </div>
  </div>
  <div style="width: 849px; align-self: stretch; padding: 12px; background: #5DE285; justify-content: flex-start; align-items: flex-start; gap: 10px; display: flex">
    <div style="flex: 1 1 0; align-self: stretch; position: relative; border-radius: 24px; justify-content: flex-start; align-items: flex-start; gap: 10px; display: flex">
      <img style="width: 587px; height: 502px; left: 119px; top: 234px; position: absolute; border-radius: 35px" src="static/images/game1.png" />
    </div>
  </div>
</div>
</div>
</body>
</html>